xdt <- data.table("w" = clonal_summary_binom$dN_to_dS_subclonal, "v" = clonal_summary_binom$dN_to_dS_clonal)
m <- glm.nb(w ~ v, data = xdt, control = glm.control(maxit = 200))
xnew <- data.table("v" = seq(0, 23, l = 10000))
ypred <- predict(m, newdata = xnew, type = "response")
plot(xdt$v, xdt$w)
lines(xnew$v, ypred, col = 2)
q95 <- qnbinom(0.025, size = m$theta, mu = xnew$v)
q05 <- qnbinom(0.975, size = m$theta, mu = xnew$v)
lines(xnew$v, q95, col = 3, lty = 2)
lines(xnew$v, q05, col = 3, lty = 2)